### ISSUE TITLE
Bubbles blink in iphone

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/chat-bubble#10]
Until scrolling is necessary, bubbles will. Link on iPhone.

**Comment by dmitrizzle** [comment]
Turned on 3D acceleration by default, it seems to help. Might have been due to elastic scroll css3 method for webkit.

**Comment by omertarikkoc** [comment]
The issue still continues. How can I fix this issue?

**Comment by dmitrizzle** [comment]
Hey @omertarik96 could you attach a gif that shows the blinking action?

**Comment by dmitrizzle** [comment]
@omertarik96 has your PR fixed the issue? If it still persist please let me know and we'll find a solution, otherwise I'll close this in the next couple days after some testing on my end.

**Comment by omertarikkoc** [comment]
Hello @dmitrizzle!

Yes, it fixed the issue so far. I have been testing for a couple of weeks with different devices (borrowing my friends' device), and everything is working great for now. 

You can close the issue, and if I have the issue again, I will open it again.

Thank you!
