### ISSUE TITLE
Better docs for advanced cases

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/chat-bubble#38]
The bubble bot tutor is OK to explain the simplest things, but a proper doc is needed for advanced cases #11

**Comment by dmitrizzle** [comment]
#45

**Comment by omertarikkoc** [comment]
What about opening a wiki page for the repo?

**Comment by dmitrizzle** [comment]
Yeah I think that what I'll do 👍

**Comment by smcnally** [comment]
Thanks for making this code available. The case attached has several chapters, a recurring "end" chapter, and a link out to an external web app that links back to another chat-bubble. I'll write / wiki it up if it's advanced enough & fits the bill. 

[bubble-chat-advanced-cases.txt](https://github.com/dmitrizzle/chat-bubble/files/1835341/bubble-chat-advanced-cases.txt)

**Comment by dmitrizzle** [comment]
Hey @smcnally, thank you for getting involved in this, I really appreciate it!

Re Wiki: I think it'd be best to just add another `.md` file and link to it from the main README. I find that Wikis are rarely read. Perhaps you can make a PR for that?

I've read through your example code, FYI there are some things which can be added (perhaps later), like [keyboard input](https://github.com/dmitrizzle/chat-bubble/blob/master/examples/3-keyboard-input.html), [natural language classifiers](https://github.com/dmitrizzle/chat-bubble/issues/45), an ability to [run javascript functions](https://github.com/dmitrizzle/chat-bubble/blob/master/examples/4-run-scripts.html), and [restoring conversation from a custom location](https://github.com/dmitrizzle/chat-bubble/blob/master/examples/2-custom-starting-point.html) (rather than the default `ice`).

There's also a case for [storing and recalling bot interactions](https://www.archie.ai/blog/storing-recalling-bot-interactions), a feature that's available under `@next` tag in NPM. That one is easy to use: `var chatWindow = new Bubbles(document.getElementById("chat"), "chatWindow", { recallInteractions: 10 } );` - simply another option that in this example shows last ten interactions when the bot is restarted.

**Comment by smcnally** [comment]
Will submit a PR with another `.md`. With luck, I'll update same for the bubble bot tutor.

> keyboard input, natural language classifiers, an ability to run javascript functions, and restoring conversation from a custom location ... storing and recalling bot interactions

are all of interest. Will follow-up there.

**Comment by dmitrizzle** [comment]
Very much appreciated, @smcnally !

**Comment by dmitrizzle** [comment]
I think the examples are great. Next step would be to convert code to work with `jsdoc` to automatically create documentation. As per scope of this issue, I'll consider this done. Thank you!
