### ISSUE TITLE
How to use this with npm

### ISSUE THREAD

**Issue by sksbtps** [dmitrizzle/chat-bubble#42]
Now, In documentation, using script tag one can include the file. But, how to use it when this is installed via npm?

**Comment by dmitrizzle** [comment]
Thanks for bringing this up @sksbtps
I've used this with Bower in Rails but I'd be happy to leave an example in doc for NPM. I think it'll be as simple as `import Bubbles from "chat-bubble"`

Are yo planning to use it with Webpack? If you let me know your setup I can tailor the example to your use.

**Comment by sksbtps** [comment]
It was just a matter of calling/loading Bubbles.js. So, It's fine now.
