### ISSUE TITLE
bubble UI total destroyed with bootstrap 

### ISSUE THREAD

**Issue by majidequbal** [dmitrizzle/chat-bubble#50]
Hi,

Bubble js is awesome but not compatible with Bootstrap. i think clearfix style getting problem.

anyone can have resolve this?

**Comment by dmitrizzle** [comment]
Hey thanks for opening this up @majidequbal - could you please share some screenshots and your setup (so that this could be reproduced)?

**Comment by dmitrizzle** [comment]
Can't act without feedback. Closing.

**Comment by majidequbal** [comment]
i reviewed code of bootstrap css finally got problem, CSS box-sizing creating problem what should i do please suggest how can i fixed box-sizing issue.

**Comment by dmitrizzle** [comment]
Hey @majidequbal! Thanks for getting back. Can you pls share a screenshot and version of Bootstrap you're using? If you don't have a solution I'll get it fixed from my end, but I'd like to know as much as possible about your setup. 😇

**Comment by dmitrizzle** [comment]
Is this what you meant by "totally destroyed"? I've used Bootstrap 4 with all the CSS and JavaScript that comes with it:

<img width="751" alt="screen shot 2018-02-22 at 4 55 38 pm" src="https://user-images.githubusercontent.com/8587882/36531755-755fb9c4-17f1-11e8-8e93-6affdbec01ff.png">

**Comment by majidequbal** [comment]
Sorry to late reply. 
Yes, Same problem is coming with bootstrap as shared you screenshot.

Ex. Word "Hi" and "Ice Cream" should be in single line.

I am using bootstrap 3.3.7.

Please help me out how can i resolve this..

**Comment by dmitrizzle** [comment]
Hmm it seems that Bootstrap CSS sheet is messing with default chat-bubble styles. Let me come up with an override CSS. I'd imagine it would cascade like this:
```
Browser defaults ↴
Bootstrap ↴
Reset code ↴
chat-bubble CSS
```

**Comment by majidequbal** [comment]
Thanks for reply

I found the error of CSS, getting problem box-sizing. if i removed, this will be worked fine but without box-sizing bootstrap grid totally destroyed.

can you fixed this issue from bubble.js

**Comment by dmitrizzle** [comment]
Hey @majidequbal could you test this PR and see if it fixes the issue for you: https://github.com/dmitrizzle/chat-bubble/pull/52

Thanks!

**Comment by dmitrizzle** [comment]
Fix is in the master branch.
