### ISSUE TITLE
Submitting value to sqlite

### ISSUE THREAD

**Issue by wakamd** [dmitrizzle/chat-bubble#59]
Feature request.
Hi
I loved the chat-bubble bot!
My limitation is that am new to python, js, and learning on the fly.
I would like to use it for a demo, but am stuck at one area. Am using web2py framework and would like that when a user types a question, the same is saved in db for processing. My humble request is that, how do i append to an sqlite db? For example, even as a user selects or types banana or ice cream, that same is inserted to the db.
Kind regards

**Comment by dmitrizzle** [comment]
Hey @wakamd,

You will need to create an JSON API endpoint for the bot on your back-end. I'm assuming you are attempting to track user's keyboard input.

First, you want the bot to send the user input to an endpoint (PUT). To do this you can follow the [keyboard input example](https://github.com/dmitrizzle/chat-bubble/blob/master/examples/3-keyboard-input.html) and utilize the `inputCallbackFn(object)` parameter. When you build this function the `object` parameter contains a key called `input` which is the text that the user has entered via they keyboard: 
```javascript
var chatWindow = new Bubbles(document.getElementById("chat"), "chatWindow", {
  inputCallbackFn: function(object) {
    sendFunction(object.input, function(){
      // this is the callback function that you can return once you've sent the text to your server
    })
  }
})
```
The callback function mentioned above can direct the chat bot to resume conversation from any endpoint in the conversation JSON ([example](https://github.com/dmitrizzle/chat-bubble/blob/master/examples/2-custom-starting-point.html)) - or you can even create a new conversation object that your server generates.

If you just want to use the button method (where user selects an answer) check out the [tutorial](https://github.com/dmitrizzle/chat-bubble/blob/master/examples/4-run-scripts.html) on how to run functions. You will need to use the same asynchronous method by creating a function with a callback parameter that runs a script once your server has responded.

To connect to server (i.e. your `sendFunction`) you could use a library like Axios, or native Fetch if the browser is new and supports it, or you can write your own XHR helper.

Hope this helps, let me know if you'd like me to clarify anything further.

**Comment by wakamd** [comment]
Thank so much. Let me follow each line you've written. I'll ask when/if
I'll be in need.
God bless!

**Comment by wakamd** [comment]
Addendum :
Am working on a bot the will allow the user to input data, and the response
will be based on the data sent to sqlite database. This data will be
processed by several machine learning functions and a response sent back to
the html view. I hope this gives you an idea of how I want that.

**Comment by dmitrizzle** [comment]
Youp, `chat-bubble` can do that. It’s built specially for that reason, actually :)

**Comment by wakamd** [comment]
Hi.
Actually am stuck. Am very new to js programming, just starting to learn it

   1. I had initially tried something like this below which connects to the
   database even though i cant figure out how to get to a folder database.
   With XHR or Axios, like the example below, how do I connect to sqlite and
   post?:
   var output = document.getElementById('output');
   document.getElementById('post').onclick = function () {

var data = document.getElementById('data').value;
axios.post('/post/server', JSON.parse(data))
.then(function (res) {
output.className = 'container';
output.innerHTML = res.data;
})
.catch(function (err) {
output.className = 'container text-danger';
output.innerHTML = err.message;
});
I looked at your examples you gave but couldn't figure out how I get to
post to my sqlite database.

   1. I wanted to use the *3-keyboard-input.html
   <http://3-keyboard-input.html>.* So the user sends random queries which
   are send to the database. I also want to store the messages/questions for
   analysis ML training, the reason for the database. So when the user message
   is stored, it can/is retrieved through a python function the interprets
   using NLP and returns a reply. In the keyboard-input example, at the place
   where it says: "Sorry, I don't get it 😕. Pls repeat? Or you can just
   click below 👇",  I had inserted the function that retrieves the message
   from the database or function and it worked well. It was exciting to see
   that.
   2.  I only want to code on how to send the question to sqlite, and have
   real-time reply on keyboard input. I had tried other methods(chats) but
   there is a delay in posting the user message to the db, so the
   reply/response that comes is not a real time reply to the current message
   but to the previous one.
   3.

var createStatement = "CREATE TABLE IF NOT EXISTS Contacts (id INTEGER
PRIMARY KEY AUTOINCREMENT, username TEXT, useremail TEXT)";

var selectAllStatement = "SELECT * FROM Contacts";

var insertStatement = "INSERT INTO Contacts (username, useremail) VALUES
(?, ?)";

var updateStatement = "UPDATE Contacts SET username = ?, useremail = ?
WHERE id=?";

var deleteStatement = "DELETE FROM Contacts WHERE id=?";

var dropStatement = "DROP TABLE Contacts";

var db = openDatabase("MyAddressBook", "1.0", "Address Book", 200000);  //
Open SQLite Database

var dataset;

var DataType;

 function initDatabase()  // Function Call When Page is ready.

{

    try {

        if (!window.openDatabase)  // Check browser is supported SQLite or
not.

        {

            alert('Databases are not supported in this browser.');

        }

        else {

            createTable();  // If supported then call Function for create
table in SQLite

        }

    }

    catch (e) {

        if (e == 2) {

            // Version number mismatch.

            console.log("Invalid database version.");

        } else {

            console.log("Unknown error " + e + ".");

        }

        return;

    }

}

function createTable()  // Function for Create Table in SQLite.

{

    db.transaction(function (tx) { tx.executeSql(createStatement, [],
showRecords, onError); });

}

function insertRecord() // Get value from Input and insert record .
Function Call when Save/Submit Button Click..

{

        var usernametemp = $('input:text[id=username]').val();

        var useremailtemp = $('input:text[id=useremail]').val();
        db.transaction(function (tx) { tx.executeSql(insertStatement,
[usernametemp, useremailtemp], loadAndReset, onError); });

        //tx.executeSql(SQL Query Statement,[ Parameters ] , Sucess Result
Handler Function, Error Result Handler Function );

}

**Comment by wakamd** [comment]
Am making some progress..but even as we discuss this,is it safe. I bumped
into this
<https://www.quora.com/How-do-I-use-SQL-js-for-accessing-a-SQLite-database-through-a-webpage>

**Comment by wakamd** [comment]
More..
I did this using XHR helper but I still cant post to my db.
// install user input textfield
  this.typeInput = function(callbackFn) {
    var inputWrap = document.createElement("div")
    inputWrap.className = "input-wrap"
    var inputText = document.createElement("textarea")
    inputText.setAttribute("placeholder", "Ask me anything...")
    var xhr = new XMLHttpRequest();
    xhr.open('GET', '/path/to/storage.sqlite', true);
    xhr.responseType = 'text';
    inputWrap.appendChild(inputText)
    inputText.addEventListener("keypress", function(e) {
      // register user input
      xhr.onload = function(e) {
      var uInt8Array = new Uint8Array(this.response);
      var db = new SQL.Database(uInt8Array);
      var contents = db.exec("INSERT INTO message (name) VALUES
('inputText');");
      };
      xhr.send();
      if (e.keyCode == 13) {
        e.preventDefault()
        typeof bubbleQueue !== false ? clearTimeout(bubbleQueue) : false //
allow user to interrupt the bot
        var lastBubble = document.querySelectorAll(".bubble.say")
        lastBubble = lastBubble[lastBubble.length - 1]
        lastBubble.classList.contains("reply") &&
        !lastBubble.classList.contains("reply-freeform")
          ? lastBubble.classList.add("bubble-hidden")
          : false
        addBubble(
          '<span class="bubble-button bubble-pick">' + this.value +
"</span>",
          function() {},
          "reply reply-freeform"
        )
        // callback
        typeof callbackFn === "function"
          ? callbackFn({
              input: this.value,
              convo: _convo,
              standingAnswer: standingAnswer
            })
          : false
        this.value = ""
      }

The html part on server response:

var miss = function() {
      chatWindow.talk(
        {
          "i-dont-get-it": {
            says: [
              "{{=reports}}"
            ],
            reply: o.convo[o.standingAnswer].reply
          }
        },
        "i-dont-get-it"
      )
    }

where {{=reports}} is the text that is returned from the function/databse
depending on how i want it.

**Comment by dmitrizzle** [comment]
Hey I’m currently traveling; will get bac once I settle 👍

**Comment by wakamd** [comment]
👍

**Comment by dmitrizzle** [comment]
You need to create a JSON API interface for your database. It should have a set of predefined, limited requests that it can process and return a JSON object. It should also be on the same IP or domain name or have CORS enabled. The delay in reply is expected but you may need to display the typing bubble in the chat-bot to simulate an experience of a user typing an answer in a real-world application. to do that, just call `chatWindow.think()` (assuming that you've initiated the bot as `var chatWindow = new Bubbles(...)`

**Comment by wakamd** [comment]
Thank you.
Good day.

**Comment by wakamd** [comment]
Hi dmitrizzle,
I did some API integration but I also worked on a button based interface
and tried the following:
html:
<form>
        
        <div id="chat">
            <div class="input-wrap">
                <input type="text" id="UserName" name="username"
class="form-control input-sm chat-input" placeholder="{{=T("Ask anything
you want")}}" />
                <button type="submit" style="position:relative;left:
50%;margin-top:55%;"class="btn btn-primary btn-md">{{=T("login")}} </button>
            </div>
        </div>
    </form>

javascript:
var btn = document.createElement("button");
btn.setAttribute("type", "submit");
inputWrap.appendChild(btn);
btn.addEventListener("click", function(e) {
    e.preventDefault();
    typeof bubbleQueue !== false ? clearTimeout(bubbleQueue) : false;
}

Every time I try with the button code I get a blank screen and the bubbles
do not apear.
Please assist in this area.
Kind regards

**Comment by dmitrizzle** [comment]
Perhaps you can share a jsFiddle or show your code in a place where I could run and see it. First thing I would suggest is to look into your console and see if there any errors.

**Comment by wakamd** [comment]
code for keyboard and Bubble.js:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wellness chat-bubble</title>

    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <link href="{{=URL('static', 'css/setup.css')}}" rel="stylesheet"
type="text/css"/>
    <link href="{{=URL('static', 'css/says.css')}}" rel="stylesheet"
type="text/css"/>
    <link href="{{=URL('static', 'css/reply.css')}}" rel="stylesheet"
type="text/css"/>
    <link href="{{=URL('static', 'css/typing.css')}}" rel="stylesheet"
type="text/css"/>
    <link href="{{=URL('static', 'css/input.css')}}" rel="stylesheet"
type="text/css"/>
    <style>
    body {
        background: #dcdde0;
    }
    .bubble-container {
        height: 100vh;
    }
    .bubble-container .input-wrap textarea {
        margin: 0;
        width: calc(100% - 30px);
    }
    </style>
</head>
<body>
    <form>
        
        <div id="chat">
            <div class="input-wrap">
                <input type="text" id="UserName" name="username"
class="form-control input-sm chat-input" placeholder="{{=T("Ask anything
you want")}}" />
                <button type="submit" style="position:relative;left:
50%;margin-top:55%;"class="btn btn-primary btn-md" >{{=T("Submit")}} <i
class="fa fa-sign-in"></i></button>
            </div>
        </div>
    </form>

    
    <script>
        // core function
        function Bubbles(container, self, options) {
            // options
            options = typeof options !== "undefined" ? options : {}
            animationTime = options.animationTime || 200 // how long it
takes to animate chat bubble, also set in CSS
            typeSpeed = options.typeSpeed || 5 // delay per character, to
simulate the machine "typing"
            widerBy = options.widerBy || 2 // add a little extra width to
bubbles to make sure they don't break
            sidePadding = options.sidePadding || 6 // padding on both sides
of chat bubbles
            recallInteractions = options.recallInteractions || 0 // number
of interactions to be remembered and brought back upon restart
            inputCallbackFn = options.inputCallbackFn || false // should we
display an input field?
            var standingAnswer = "ice" // remember where to restart convo
if interrupted
            var _convo = {} // local memory for conversation JSON object
            //--> NOTE that this object is only assigned once, per session
and does not change for this
            //  constructor name during open session.
            // local storage for recalling conversations upon restart
            var localStorageCheck = function() {
                var test = "chat-bubble-storage-test"
                try {
                    localStorage.setItem(test, test)
                    localStorage.removeItem(test)
                    return true
                    } catch (error) {
                        console.error(
                            "Your server does not allow storing data
locally. Most likely it's because you've opened this page from your
hard-drive. For testing you can disable your browser's security or start a
localhost environment."
                            )
                        return false
                        }
                }
            var localStorageAvailable = localStorageCheck() &&
recallInteractions > 0
            var interactionsLS = "chat-bubble-interactions"
            var interactionsHistory =
                (localStorageAvailable &&
                 JSON.parse(localStorage.getItem(interactionsLS))) ||
                []
            // prepare next save point
            interactionsSave = function(say, reply) {
                if (!localStorageAvailable) return
                // limit number of saves
                if (interactionsHistory.length > recallInteractions)
                interactionsHistory.shift() // removes the oldest (first)
save to make space
                // do not memorize buttons; only user input gets memorized:
                if (
                    // `bubble-button` class name signals that it's a button
                    say.includes("bubble-button") &&
                    // if it is not of a type of textual reply
                    reply !== "reply reply-freeform" &&
                    // if it is not of a type of textual reply or memorized
user choice
                    reply !== "reply reply-pick"
                    )
                    // ...it shan't be memorized
                    return
                    // save to memory
                    interactionsHistory.push({ say: say, reply: reply })
                    }
            // commit save to localStorage
            interactionsSaveCommit = function() {
                if (!localStorageAvailable) return
                localStorage.setItem(interactionsLS,
JSON.stringify(interactionsHistory))
                }
            // set up the stage
            container.classList.add("bubble-container")
            var bubbleWrap = document.createElement("div")
            bubbleWrap.className = "bubble-wrap"
            container.appendChild(bubbleWrap)
            // install user input textfield
            this.typeInput = function(callbackFn) {
                var inputWrap = document.createElement("div")

                inputWrap.className = "input-wrap"
                var inputText = document.getElementById("UserName");

                inputWrap.appendChild(inputText)
                inputText.addEventListener("keypress", function(e) {
                    // register user input
                    if (e.keyCode == 13) {
                        e.preventDefault()
                        typeof bubbleQueue !== false ?
clearTimeout(bubbleQueue) : false // allow user to interrupt the bot

                        var lastBubble =
document.querySelectorAll(".bubble.say")
                        lastBubble = lastBubble[lastBubble.length - 1]
                        lastBubble.classList.contains("reply") &&
                            !lastBubble.classList.contains("reply-freeform")
                        ? lastBubble.classList.add("bubble-hidden")
                        : false
                        addBubble(
                            '<span class="bubble-button bubble-pick">' +
this.value + "</span>",
                            function() {},
                            "reply reply-freeform"
                            )
                        var btn = document.createElement("button");
                        btn.setAttribute("type", "submit");
                        inputWrap.appendChild(btn);
                        btn.addEventListener("click", function(e) {
                            e.preventDefault();
                            typeof bubbleQueue !== false ?
clearTimeout(bubbleQueue) : false;
                            }
                        // callback
                        typeof callbackFn === "function"
                        ? callbackFn({
                            input: this.value,
                            convo: _convo,
                            standingAnswer: standingAnswer
                            })
                        : false
                        this.value = ""
                        }
                    })
                container.appendChild(inputWrap)
                bubbleWrap.style.paddingBottom = "100px"
                inputText.focus()
                }
            inputCallbackFn ? this.typeInput(inputCallbackFn) : false
            // init typing bubble
            var bubbleTyping = document.createElement("div")
            bubbleTyping.className = "bubble-typing imagine"
            for (dots = 0; dots < 3; dots++) {
                var dot = document.createElement("div")
                dot.className = "dot_" + dots + " dot"
                bubbleTyping.appendChild(dot)
                }
            bubbleWrap.appendChild(bubbleTyping)
            // accept JSON & create bubbles
            this.talk = function(convo, here) {
                // all further .talk() calls will append the conversation
with additional blocks defined in convo parameter
                _convo = Object.assign(_convo, convo) // POLYFILL REQUIRED
FOR OLDER BROWSERS
                this.reply(_convo[here])
                here ? (standingAnswer = here) : false
                }
            var iceBreaker = false // this variable holds answer to whether
this is the initative bot interaction or not
            this.reply = function(turn) {
                iceBreaker = typeof turn === "undefined"
                turn = !iceBreaker ? turn : _convo.ice
                questionsHTML = ""
                if (!turn) return
                if (turn.reply !== undefined) {
                    turn.reply.reverse()
                    for (var i = 0; i < turn.reply.length; i++) {
                        ;(function(el, count) {
                            questionsHTML +=
                                '<span class="bubble-button"
style="animation-delay: ' +
                                animationTime / 2 * count +
                                'ms" onClick="' +
                                self +
                                ".answer('" +
                                el.answer +
                                "', '" +
                                el.question +
                                "');this.classList.add('bubble-pick')\">" +
                                el.question +
                                "</span>"
                            })(turn.reply[i], i)
                        }
                    }
                orderBubbles(turn.says, function() {
                    bubbleTyping.classList.remove("imagine")
                    questionsHTML !== ""
                    ? addBubble(questionsHTML, function() {}, "reply")
                    : bubbleTyping.classList.add("imagine")
                    })
                }
            // navigate "answers"
            this.answer = function(key, content) {
                var func = function(key) {
                    typeof window[key] === "function" ? window[key]() :
false
                    }
                _convo[key] !== undefined
                ? (this.reply(_convo[key]), (standingAnswer = key))
                : func(key)
                // add re-generated user picks to the history stack
                if (_convo[key] !== undefined && content !== undefined) {
                    interactionsSave(
                        '<span class="bubble-button reply-pick">' + content
+ "</span>",
                        "reply reply-pick"
                        )
                    }
                }
            // api for typing bubble
            this.think = function() {
                bubbleTyping.classList.remove("imagine")
                this.stop = function() {
                    bubbleTyping.classList.add("imagine")
                    }
                }
            // "type" each message within the group
            var orderBubbles = function(q, callback) {
                var start = function() {
                    setTimeout(function() {
                        callback()
                        }, animationTime)
                    }
                var position = 0
                for (
                    var nextCallback = position + q.length - 1;
                    nextCallback >= position;
                    nextCallback--
                    ) {
                    ;(function(callback, index) {
                        start = function() {
                            addBubble(q[index], callback)
                            }
                        })(start, nextCallback)
                    }
                start()
                }
            // create a bubble
            var bubbleQueue = false
            var addBubble = function(say, posted, reply, live) {
                reply = typeof reply !== "undefined" ? reply : ""
                live = typeof live !== "undefined" ? live : true // bubbles
that are not "live" are not animated and displayed differently
                var animationTime = live ? this.animationTime : 0
                var typeSpeed = live ? this.typeSpeed : 0
                // create bubble element
                var bubble = document.createElement("div")
                var bubbleContent = document.createElement("span")
                bubble.className = "bubble imagine " + (!live ? " history "
: "") + reply
                bubbleContent.className = "bubble-content"
                bubbleContent.innerHTML = say
                bubble.appendChild(bubbleContent)
                bubbleWrap.insertBefore(bubble, bubbleTyping)
                // answer picker styles
                if (reply !== "") {
                    var bubbleButtons =
bubbleContent.querySelectorAll(".bubble-button")
                    for (var z = 0; z < bubbleButtons.length; z++) {
                        ;(function(el) {
                            if
(!el.parentNode.parentNode.classList.contains("reply-freeform"))
                                el.style.width = el.offsetWidth -
sidePadding * 2 + widerBy + "px"
                                })(bubbleButtons[z])
                        }
                    bubble.addEventListener("click", function() {
                        for (var i = 0; i < bubbleButtons.length; i++) {
                            ;(function(el) {
                                el.style.width = 0 + "px"
                                el.classList.contains("bubble-pick") ?
(el.style.width = "") : false
                                el.removeAttribute("onclick")
                                })(bubbleButtons[i])
                            }
                        this.classList.add("bubble-picked")
                        })
                    }
                // time, size & animate
                wait = live ? animationTime * 2 : 0
                minTypingWait = live ? animationTime * 6 : 0
                if (say.length * typeSpeed > animationTime && reply == "") {
                    wait += typeSpeed * say.length
                    wait < minTypingWait ? (wait = minTypingWait) : false
                    setTimeout(function() {
                        bubbleTyping.classList.remove("imagine")
                        }, animationTime)
                    }
                live && setTimeout(function() {
                    bubbleTyping.classList.add("imagine")
                    }, wait - animationTime * 2)
                bubbleQueue = setTimeout(function() {
                    bubble.classList.remove("imagine")
                    var bubbleWidthCalc = bubbleContent.offsetWidth +
widerBy + "px"
                    bubble.style.width = reply == "" ? bubbleWidthCalc : ""
                    bubble.style.width = say.includes("<img src=")
                    ? "50%"
                    : bubble.style.width
                    bubble.classList.add("say")
                    posted()
                    // save the interaction
                    interactionsSave(say, reply)
                    !iceBreaker && interactionsSaveCommit() // save point
                    // animate scrolling
                    containerHeight = container.offsetHeight
                    scrollDifference = bubbleWrap.scrollHeight -
bubbleWrap.scrollTop
                    scrollHop = scrollDifference / 200
                    var scrollBubbles = function() {
                        for (var i = 1; i <= scrollDifference / scrollHop;
i++) {
                            ;(function() {
                                setTimeout(function() {
                                    bubbleWrap.scrollHeight -
bubbleWrap.scrollTop > containerHeight
                                    ? (bubbleWrap.scrollTop =
bubbleWrap.scrollTop + scrollHop)
                                    : false
                                    }, i * 5)
                                })()
                            }
                        }
                    setTimeout(scrollBubbles, animationTime / 2)
                    }, wait + animationTime * 2)
                }
            // recall previous interactions
            for (var i = 0; i < interactionsHistory.length; i++) {
                addBubble(
                    interactionsHistory[i].say,
                    function() {},
                    interactionsHistory[i].reply,
                    false
                    )
                }
            }
        // below functions are specifically for WebPack-type project that
work with import()
        // this function automatically adds all HTML and CSS necessary for
chat-bubble to function
        function prepHTML(options) {
            // options
            var options = typeof options !== "undefined" ? options : {}
            var container = options.container || "chat" // id of the
container HTML element
            var relative_path = options.relative_path ||
"./node_modules/chat-bubble/"
            // make HTML container element
            window[container] = document.createElement("div")
            window[container].setAttribute("id", container)
            document.body.appendChild(window[container])
            // style everything
            var appendCSS = function(file) {
                var link = document.createElement("link")
                link.href = file
                link.type = "text/css"
                link.rel = "stylesheet"
                link.media = "screen,print"
                document.getElementsByTagName("head")[0].appendChild(link)
                }
            appendCSS(relative_path + "component/styles/input.css")
            appendCSS(relative_path + "component/styles/reply.css")
            appendCSS(relative_path + "component/styles/says.css")
            appendCSS(relative_path + "component/styles/setup.css")
            appendCSS(relative_path + "component/styles/typing.css")
            }
        // exports for es6
        if (typeof exports !== "undefined") {
            exports.Bubbles = Bubbles
            exports.prepHTML = prepHTML
            }
        </script>

    <script>
        // initialize by constructing a named function...
        // ...and add text processing plugin:
        var chatWindow = new Bubbles(document.getElementById("chat"),
"chatWindow", {
            // the one that we care about is inputCallbackFn()
            // this function returns an object with some data that we can
process from user input
            // and understand the context of it
            // this is an example function that matches the text user typed
to one of the answer bubbles
            // this function does no natural language processing
            // this is where you may want to connect this script to NLC
backend.
            inputCallbackFn: function(o) {
                // add error conversation block & recall it if no answer
matched
                var miss = function() {
                    chatWindow.talk(
                        {
                            "i-dont-get-it": {
                                says: [
                                    "{{=message}}"
                                    //"messages will come in here. How I
pray that Almighty Go will give me a break through on this and notget
battered by It guys."
                                    ],
                                reply: o.convo[o.standingAnswer].reply
                                }
                            },
                        "i-dont-get-it"
                        )
                    }
                // do this if answer found
                var match = function(key) {
                    setTimeout(function() {
                        chatWindow.talk(convo, key) // restart current
convo from point found in the answer
                        }, 600)
                    }
                // sanitize text for search function
                var strip = function(text) {
                    return
text.toLowerCase().replace(/[\s.,\/#!$%\^&\*;:{}=\-_'"`~()]/g, "")
                    }
                // search function
                var found = false
                o.convo[o.standingAnswer].reply.forEach(function(e, i) {
                    strip(e.question).includes(strip(o.input)) &&
o.input.length > 0
                    ? (found = e.answer)
                    : found ? null : (found = false)
                    })
                found ? match(found) : miss()
                }
            }) // done setting up chat-bubble
        // conversation object defined separately, but just the same as in
the
        // "Basic chat-bubble Example" (1-basics.html)
        var convo = {
            ice: {
                says: ["Hi", "Would you like banana or ice cream?"],
                reply: [
                    {
                        question: "Banana",
                        answer: "banana"
                        },
                    {
                        question: "Ice Cream",
                        answer: "ice-cream"
                        }
                    ]
                },
            banana: {
                says: ["🍌"],
                reply: [
                    {
                        question: "Start Over",
                        answer: "ice"
                        }
                    ]
                },
            "ice-cream": {
                says: ["🍦"],
                reply: [
                    {
                        question: "Start Over",
                        answer: "ice"
                        }
                    ]
                }
            }
        // pass JSON to your function and you're done!
        chatWindow.talk(convo)
        </script>
    </body>
    </html>
N/B
Am still very new in javascript
Kind regards

**Comment by dmitrizzle** [comment]
Can you give me a **link** to a working file online with this code? I don't mind helping you along but I can't spend too much time setting things up on my end.

**Comment by wakamd** [comment]
I have it working on localhost, with web2py framework. Am not sure if you
can do with web2py.

**Comment by wakamd** [comment]
Sorry , I hope I understand that you need this.
See attached.

**Comment by dmitrizzle** [comment]
I need a way to run this code and see any errors that JS has to spits out, which is very difficult with what you're giving me. I suggest you start by opening browser console and checking any error messages you're having first. That's exactly what I would do with your code, if I could run it.

**Comment by wakamd** [comment]
I've shared an item with you:

bubbleness.zip
https://drive.google.com/file/d/1Vj7TiloVOSpd3ek6wd3eJNexHnLLEZiq/view?usp=sharing&ts=5b67585b

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by wakamd** [comment]
I've forwarded it from my google drive.
I hope you got it.
Regards

**Comment by wakamd** [comment]
link to file is also here:
https://drive.google.com/open?id=1Vj7TiloVOSpd3ek6wd3eJNexHnLLEZiq

**Comment by wakamd** [comment]
Hi dmitrizzle,
Sorry I totally misunderstood you. But after digging around, I managed to
upload the files to pythonanywhere.
See this:
https://hestconvo.pythonanywhere.com/hest_convo/default/view_searches
Kind regards

**Comment by wakamd** [comment]
The pythonanywhere login detail: username:hestconvo, pw: potomacuas123**

**Comment by dmitrizzle** [comment]
Hey @wakamd FYI this conversation is not private, your login details could be seen by anyone. I suggest you change them. Also, they didn't work for me as the service requires email address rather than user name.

Let's move this conversation to email instead. Please send your reply to d at analog dot cafe.
