### ISSUE TITLE
HTML code help

### ISSUE THREAD

**Issue by ghost** [dmitrizzle/chat-bubble#62]
Hey. I apologize in advance for bad English.
I need to understand how you can call question bubbles and answer bubbles as easy as possible for example test ("123", question)
I plan to connect to the entire project ai speech kit. Unfortunately there is not enough knowledge to understand how to manually call tiles from html code.

**Comment by dmitrizzle** [comment]
What do you mean by "how to manually call tiles from html code" please?

**Comment by JensThanx** [comment]
The usual way to call any question/answer bubbles is with "chatWindow.talk(convo)".
Where "convo" is the conversation (which can be as simple as one question and one answer option).
Note that a "convo" is an data object. So, there is no thing as a single method "say("How are you?", question)".
The sample code in the quick start section gives a good impression what a very simple conversation would look like.
A most easy way would be probably:
```
chatWindow.talk(
{"ice": {"says": [ "How are you?" ],
      "reply" : [{"question" : "Good.",
          "answer" : "good"}]}
})
```
To connect with AI in the background you need to do a little more. Look at the code of example-3 to get an idea how keyboard input is processed.

**Comment by dmitrizzle** [comment]
Looks like this is solved, thank you Jens!
