### ISSUE TITLE
Please provide an Exmple for NPM

### ISSUE THREAD

**Issue by ashish9308** [dmitrizzle/chat-bubble#63]
Please give me an example like how I can use this with MEAN stack.
I'm using AngularJS 1.0 with NodeJS and Express and reason behind using this is because I want to store the chat conversation in MongoDB.
### Bug or feature request?
Let me know what type of issue this is.

### If it's a bug, please provide the full method to reproduce.
How did you end up seeing the bug? What steps did you take to see it?

**Comment by dmitrizzle** [comment]
`yarn add chat-bubble` or `npm install chat-bubble`

ES6:
```javascript
// all of this is from readme
import { Bubbles, prepHTML } from "../node_modules/chat-bubble/component/Bubbles.js"
prepHTML({relative_path: "../node_modules/chat-bubble/"})
const chatWindow = new Bubbles(document.getElementById('chat'), "chatWindow");

// use your own fetch polyfill/ponyfill or whatever means you get your XHR connections
fetch("your-api-endpoint").then(r => r.json()).then(response => {
  // assuming the API returns properly formatted JSON document for chat-bubble
  chatWindow.talk(response);
});
```

I think this should cover it. Note that you need to create an API endpoint via Express that prints out the JSON that you'd be using in the chat.

You could make that endpoint spit out only small, relevant bits of conversation and load new JSON whenever the replies change on the server.
