### ISSUE TITLE
After User Inputs again want to switch back to json chat

### ISSUE THREAD

**Issue by ashish9308** [dmitrizzle/chat-bubble#65]
After taking some input from users and validation like this 
if(a.length == 6)  
          {
        chatWindow.talk(
        {
          "sapcode": {
            says: [
              "Ok Thankssss...","Please Enter Your Employee ID."
            ],
            reply: o.convo[o.standingAnswer].reply
                  
              }
          
          },
            
            "sapcode"
          )
               
          }

Now I want to ask user to Do you want to submit this form ? And with reply Yes and No 
where these code should be added exactly. I'm new in this could you please help me.

**Comment by dmitrizzle** [comment]
Not sure I understand, Ashish. What are you trying to achieve?

**Comment by ashish9308** [comment]
After the callback (inputCallbackFn) again I want to ask some question to user which is inside my  convo how to call this 
For Example :

var convo = {
  ice: {
    says: ["Would you like to submit the result?"],
    reply: [
      {
        question: "Yes",
        answer: "yes"
      },
      {
        question: "No",
        answer: "no"
      }
    ]
  }

**Comment by dmitrizzle** [comment]
Please follow this example: https://github.com/dmitrizzle/chat-bubble/blob/master/examples/1-basics.html
