### ISSUE TITLE
Get User data selected. If user select banana how to save this into a var?

### ISSUE THREAD

**Issue by Aljaber808** [dmitrizzle/chat-bubble#86]
### Bug or feature request?
Let me know what type of issue this is.

### If it's a bug, please provide the full method to reproduce.
How did you end up seeing the bug? What steps did you take to see it?

**Comment by dmitrizzle** [comment]
Hey @Aljaber808, you can run a function that can store user response to a variable, localStorage, or wherever you like. Check out [the example](https://github.com/dmitrizzle/chat-bubble/blob/master/examples/4-run-scripts.html) that demonstrates the concept.
