### ISSUE TITLE
[Enhancement] 1 to 10 scale

### ISSUE THREAD

**Issue by sabatale** [dmitrizzle/chat-bubble#92]
### Feature request
More like an example I'd like to have a simple 1 to 10 choice (rating). I understand there is no standard component beyond the reply, but is there any sample I can use without leveraging functions?

Thanks for building chat-bubble!

**Comment by dmitrizzle** [comment]
If you don't want to leverage functions, you may give 10 answer choices to the user which could either appear as bubbles (same as basic example) or by using keyboard input (however, if your user types something that can't be fuzzy-matched to your options, it may not work in which case using NLC may be better). Does that help?
