### ISSUE TITLE
RASA instructions not working for me. Can I get some help?

### ISSUE THREAD

**Issue by ilyasjamil** [dmitrizzle/chat-bubble#93]
my bot is running fine and I have everything rasa related setup correctly. I wanted to test it on the web using your UI but your rasa demo instructions didnt work for me for some reason. When I open the  rasa demo html file on my browser after seting up the server, I still get the same default demo, which is just the bot saying 'hi' . My chatbot is not there. What did I do wrong?

**Comment by ilyasjamil** [comment]
solution: I had to replace 0.0.0.0 with localhost on the base url.

**Comment by dmitrizzle** [comment]
Thank you for posting your solution, @ilyasjamil!
