### ISSUE TITLE
How do I make the output of the chatbot make new lines ("\n")?

### ISSUE THREAD

**Issue by ilyasjamil** [dmitrizzle/chat-bubble#94]
So my Rasa chatbot code returns a paragraph with "\n" at the end of each line to make a new line. But when I use your Chat-bubble interface with the Rasa demo it gets ignored and every line is stacked together with the other one. What should I make the chatbot say to make a newline if \n does not work?

**Comment by dmitrizzle** [comment]
Hey @ilyasjamil, have you tried replacing `\n` with `<br />`? `text.replace(/\\n/g, "<br />");`

**Comment by dmitrizzle** [comment]
Alternatively, you may format your text into paragraphs with `<p>`-tags or whichever way you like with HTML and CSS.

**Comment by ilyasjamil** [comment]
> Hey @ilyasjamil, have you tried replacing `\n` with `<br />`? `text.replace(/\\n/g, "<br />");`

thank you!
