### ISSUE TITLE
I used  your rasa demo html page for my rasa project and now I want to deploy in AWS using docker

### ISSUE THREAD

**Issue by ilyasjamil** [dmitrizzle/chat-bubble#96]
I have an image for rasa actions server, and the rasa server, but I dont know how to integrate your html file. my plan is to deploy in AWS. Do I need to make another image for the html page only? or can I just deploy the images I have currently and add the html file to AWS without a docker image? thanks.

**Comment by dmitrizzle** [comment]
Hey @ilyasjamil,

I think it would work best (for ease and scalability) if you separate your chatbot as a web app from your RASA API server. With `chat-bubble` you can simply use a static server to host the front-end. Anything S3-compatible will do, you can even host your static code on Github Pages.

**Comment by ilyasjamil** [comment]
thanks!
